# fly.toml - Configuration for Moondream Discord Bot

app = "moondream-discord-bot"
primary_region = "sea"

[build]
  # No buildpacks - use Dockerfile instead

[env]
  PYTHONUNBUFFERED = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Don't stop machines for Discord bot (needs to stay running)
  auto_start_machines = true
  min_machines_running = 1  # Keep at least one instance running

[processes]
  app = "python bot.py"  # Main Discord bot process

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2

# Optional volume for data persistence
[mounts]
  source = "moondream_data"
  destination = "/data"

# Health check is optional for Discord bots
[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
